# Start and end of the season.
# The script ignores any events outside of this range.
startDate: 09/01/2017
endDate: 05/01/2018

# Date of bag and tag
bagDate: 02/20/2018

# The code for the business scanner
businessScanner: "105059"

# The root directory for this years data files
dataRoot: data/2018

# The output filename
output: timecard.xlsx

# The list of tracks and the minimum hours in each
hours:
  Technical: 90.0
  Business: 10.0
  Post-Bag: 16.0

