# Start and end of the season.
# The script ignores any events outside of this range.
startDate: 01/01/2017
endDate: 05/01/2017

kickOff: 01/09/2017

# Date of bag and tag
bagDate: 02/21/2017

# The code for the business scanner
businessScanner: "105059"

# The root directory for this years data files
dataRoot: data/2017

# The output filename
output: timecard.xlsx

# The list of tracks and the minimum hours in each
tracks:
  Pre-season:
    hours: 1000.0
  Technical:
    hours: 90.0
  Business:
    hours: 10.0
  Post-Bag:
    hours: 16.0

